
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7071
spring:
  application:
    name: bookdetails
  datasource:
    url: jdbc:h2:mem:db1
    username: sa
    password: password
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true



