
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7072
spring:
  application:
    name: bookdetails
  data:
    mongodb:
      uri: mongodb+srv://anagh11:anagh11@bookcluster.dl7kn.mongodb.net/?retryWrites=true&w=majority&appName=BookCluster
      database: bookdbbook





